# Generated by Django 5.0.1 on 2024-02-08 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('photos', '0004_alter_photopet_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photocomment',
            name='photo_pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='photos.photopet'),
        ),
        migrations.AlterField(
            model_name='photolike',
            name='photo_pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='photos.photopet'),
        ),
    ]
