# Generated by Django 5.0.1 on 2024-02-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_pet_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_photo',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
    ]
