# Generated by Django 5.0.1 on 2024-01-29 10:57

import Petstagram_project.photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_photopet_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photopet',
            name='photo',
            field=models.ImageField(upload_to='photos_pet/', validators=[Petstagram_project.photos.validators.MaxSizeImageValidator(limit_value=6217728)]),
        ),
    ]
